### ISSUE TITLE
How/when to clear old sessions?

### ISSUE THREAD

**Issue by noctivityinc** [roidrage/redis-session-store#70]
How would we go about clearing out old session data from Redis so the db doesn't grow too large?  Also, when would you recommend we do that?

**Comment by meatballhat** [comment]
@noctivityinc Hey :smile_cat:!  This is the intent of the `expire_after` option, as it uses `SETEX` instead of plain `SET`.  The existence of the behavior with `SET` is there for setups where Redis is managed out of band, or for applications like internal admin tools where infinite sessions for small user bases might be desired.
